export enum EducationBackgroundEnum {
  MIDDLE_SCHOOL = "MIDDLE_SCHOOL",
  HIGH_SCHOOL = "HIGH_SCHOOL",
  DIPLOMA = "DIPLOMA",
  BACHELOR_DEGREE = "BACHELOR_DEGREE",
  MASTER_DEGREE = "MASTER_DEGREE",
  DOCTORAL_DEGREE = "DOCTORAL_DEGREE",
  POST_DOCTORAL = "POST_DOCTORAL",
}

export enum ContactEnum {
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  NONE = "NONE",
}
